kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sjcvolclaim
  namespace: mapr-sjc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G
  storageClassName: influxdb-maprfs
