# Copyright (c) 2009 & onwards. MapR Tech, Inc., All rights reserved
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: influxdbsjc-maprfs
   namespace: mapr-sjc
provisioner: mapr.com/maprfs
parameters:
    restServers: "changeme:8443"
    cluster: "mapr600"
    cldbHosts: "changeme"
    securityType: "secure"
    ticketSecretName: "mapr-ticket-secret"
    ticketSecretNamespace: "mapr-sjc"
    maprSecretName: "mapr-provisioner-secrets"
    maprSecretNamespace: "mapr-sjc"
    namePrefix: "influx"
    mountPrefix: "/sjc"
    advisoryquota: "100M"
#   quota: "500M"
#   type: "rw"
#   mount: "1"
#   readonly: "0"
#   replication: "3"
#   schedule: "2"
